name: apppresenca
description: A new Flutter project.

# Impede publicação acidental no pub.dev
publish_to: 'none'

# Versão do aplicativo
version: 1.0.0+1

environment:
  sdk: ^3.9.0-76.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # just_audio: ^0.9.36
  path_provider: ^2.0.14
  record: ^3.0.0
  just_audio: ^0.9.37
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para adicionar assets, descomente e adicione seus arquivos:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para adicionar fontes personalizadas, siga este modelo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
