name: apppresenca
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-76.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Pacotes para Mobile
  path_provider: ^2.0.14           # ❌ Não compatível com Web. Usar shared_preferences ou universal_html na Web.
  record: ^3.0.0                   # ⚠️ Funciona com limitações na Web. Verificar suporte ao MediaRecorder.
  just_audio: ^0.9.37              # ⚠️ Funciona na Web, mas com limitações (sem efeitos avançados).
  http: ^1.4.0                     # ✅ Compatível com Web e Mobile.

  # Sugestões para Web (não habilitadas por padrão):
  # universal_html: ^2.2.3         # ✅ Alternativa ao path_provider para Web (manipulação básica de arquivos).
  # shared_preferences: ^2.2.2     # ✅ Armazenamento local simples compatível com Web.
  # flutter_web_plugins:           # ✅ Permite adaptar plugins para multiplataforma (avançado).
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Caso queira adicionar assets, imagens ou sons, pode fazer aqui:
  # assets:
  #   - assets/audio/
  #   - assets/images/
